// Generated by @tanstack/router-plugin from the files under routes/. Committed, never edited by hand.
// Every file under routes/ becomes a typed route here; a route that has no file does not exist.
